# Usa uma imagem base do Python
FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia dependências e instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia a aplicação
COPY app.py .

# Expõe a porta do Flask
EXPOSE 5000

# Comando para rodar o app
CMD ["python", "app.py"]
